### PR TITLE
TOML config file support

### LINKED ISSUE #28: Feature: TOML config file support
# Description

While it's great to provide flags to support the substitution and customization of some settings like the `api url` or the `model name` -- it can be a little inconvenient for the user to constantly do it every time they want to use the tool. This issue brings the idea of using [TOML](https://toml.io/en/) config files directly with `explainer.js` by having a `.explainer-config.toml` file in the `home` directory.

A `TOML` file's structure is something like:

```
model = "gpt-4o"
api_key = "sk-...."
# etc...
```

This would require having a `TOML` parser, and automatically detecting any configuration substitutions in the tool! A great `TOML` parser that is maintained is [j-toml](https://github.com/LongTengDao/j-toml/tree/master/docs/English) !

# Usage

An example of usage would be: 

```bash
node index.js examples/bubble_sort.js
```

Where the the `TOML` file can contain any options that the tool accepts!

Then the behavior of the tool would be just like it is normally, with the exception of using the `config` options provided by the `TOML` file, however, CLI given options take precedence over the options provided in the `TOML` file!

### PR DESCRIPTION
**Pull request by Mounayer**
# Description

Closes #28.

Added a new feature to support config options provided by a [TOML](https://toml.io/en/) `.explainer-config.toml` file in the `home` directory: 
- All options provided by the config file will only work if no equivalent option is given in the CLI, as the CLI takes precedence over `TOML`. 
- Used [j-toml](https://github.com/LongTengDao/j-toml/tree/master/docs/English) as the `TOML` file parser.
- Added an example of a `TOML` config file in the `examples` folder.
- Updated `README.md` to explain the new feature.

## Testing

Visit the new `TOMl` file added in the `examples` folder, and add your `API_KEY` in there, i.e.:

```
# Any of these config options can or can not be provided
# Feel free to place this file in your home directory, i.e: cp examples/.explainer-config.toml ~

apiKey = "YOUR_API_KEY"
baseURL = "https://api.groq.com/"
temperature = 0.8 # between 0.1 and 2
model = "llama-3.1-70b-versatile" # any supported model
output = "testingToml.txt" # will overwrite a file with the same name
tokenUsage = true # can be true or false
```

Then copy it to your `home` directory.

### Test 1

Use `explainer` with the `TOML` file, i.e.:
```bash
node index.js examples/bubble_sort.js
```

Make sure that all the flags have been processed

### Test 2

Try different combinations in the `TOML` config file, i.e.:

```
temperature = 0.8 # between 0.1 and 2
model = "llama-3.1-70b-versatile" # any supported model
output = "testingToml.txt" # will overwrite a file with the same name
```

And provide extra options in the CLI tool, i.e.:

```bash
node index.js examples/bubble_sort.js -u
```

This should not only process the options in the `TOML` file, but also the `-u` token usage flag

### Test 3

Try to override configs given in the `TOML` file, i.e., let's say your `TOML` file is:

```
temperature = 0.8 # between 0.1 and 2
model = "llama-3.1-70b-versatile" # any supported model
output = "testingToml.txt" # will overwrite a file with the same name
```

But you provide a different temperature when using the tool, i.e.:

```bash
node index.js examples/bubble_sort.js -t 0.9
```
It should use the CLI given temperature instead.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -16,28 +17,37 @@ program
...
 
 program
-  .addOption(new Option('-a, --api-key <your-key>', 'define API key to use for processing defined in .env file').env('API_KEY').makeOptionMandatory())
+  .addOption(new Option('-a, --api-key <your-key>', 'define API key to use for processing defined in .env file').env('API_KEY'))
   .addOption(new Option('-b, --baseURL <url>', 'define the base URL to use for processing defined in .env file').default('https://api.groq.com/').env('BASE_URL'))
   .addOption(new Option('-m, --model <model-name>', 'define the model to use for processing').default('llama-3.1-70b-versatile').env('MODEL_NAME'))
   .addOption(new Option('-o, --output <file>', 'define an output file with valid extension to be able access the output'))
   .addOption(new Option('-t, --temperature <number>', 'define temperature of chat completion between 0 to 2').default(1).argParser(parseFloat))
-  .addOption(new Option('-u, --token-usage', 'specify if you want to see tokens that were sent in the prompt and the number of tokens that were returned'))
+  .addOption(new Option('-u, --token-usage', 'specify if you want to see tokens that were sent in the prompt and the number of tokens that were returned'));
```
Comment (aamfahim) [inline index.js]: not necessary

File: examples/.explainer-config.toml [hunk 2]
```diff
@@ -0,0 +1,9 @@
+# Any of these config options can or can not be provided
```
Comment (aamfahim) [inline examples/.explainer-config.toml]: this statement is incorrect. If the user choses to not define `apiKey` in `.toml` file it will not work. User either has to define it in `.env` file, in `.toml` file or via command line. It should be clarified which ones have default value defined already aka doesn't necessitate a definition for the tool to work and which ones can modified for user configuration.

File: examples/.explainer-config.toml [hunk 3]
```diff
@@ -0,0 +1,9 @@
+# Any of these config options can or can not be provided
+# Feel free to place this file in your home directory, i.e: cp examples/.explainer-config.toml ~
+
+apiKey = "YOUR_API_KEY"
+baseURL = "https://api.groq.com/"
+temperature = 0.8 # between 0.1 and 2
+model = "llama-3.1-70b-versatile" # any supported model
+output = "testingToml.txt" # will overwrite a file with the same name
+tokenUsage = true # can be true or false
```
Comment (aamfahim) [inline examples/.explainer-config.toml]: I'd prefer it be `false` by default.

File: examples/.explainer-config.toml [hunk 4]
```diff
@@ -0,0 +1,9 @@
+# Any of these config options can or can not be provided
+# Feel free to place this file in your home directory, i.e: cp examples/.explainer-config.toml ~
+
+apiKey = "YOUR_API_KEY"
+baseURL = "https://api.groq.com/"
+temperature = 0.8 # between 0.1 and 2
+model = "llama-3.1-70b-versatile" # any supported model
+output = "testingToml.txt" # will overwrite a file with the same name
```
Comment (aamfahim) [inline examples/.explainer-config.toml]: `output.txt` would be a more meaningful name than this.

File: examples/.explainer-config.toml [hunk 5]
```diff
@@ -0,0 +1,9 @@
+# Any of these config options can or can not be provided
+# Feel free to place this file in your home directory, i.e: cp examples/.explainer-config.toml ~
+
+apiKey = "YOUR_API_KEY"
+baseURL = "https://api.groq.com/"
+temperature = 0.8 # between 0.1 and 2
```
Comment (aamfahim) [inline examples/.explainer-config.toml]: this should follow the already defined default value for temperature in `index.js`
https://github.com/aamfahim/explainer.js/blob/29c31bd8ab656243296f7370bf41014c40ca75fe/index.js#L23

File: README.md [hunk 6]
```diff
@@ -109,6 +110,23 @@ or
 node index.js examples/bubble_sort.js examples/selection_sort.js
 ```
 
+### TOML Config
+
+You can create a [TOML](https://toml.io/en/) `.explainer-config.toml` config file that contains all of your options for the tool and place it in your `home` directory, i.e. (or simply modify and copy the one that is in the `examples directory`):
+```
```
Comment (aamfahim) [inline README.md:127]: > MD040/fenced-code-language: Fenced code blocks should have a language specified markdownlint [MD040](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md040.md)
> MD031/blanks-around-fences: Fenced code blocks should be surrounded by blank lines markdownlint [MD031](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md031.md)
```suggestion

```toml
```

File: README.md [hunk 7]
```diff
@@ -109,6 +110,23 @@ or
...
+# Any of these config options can or can not be provided
+# Feel free to place this file in your home directory, i.e: cp examples/.explainer-config.toml ~
```
Comment (aamfahim) [inline README.md]: I think it'd better to have this in the markdown as a bash code block opposed to in the file itself. Also, what if the user is not using a Linux system? How would they copy it over if they are using windows?

File: examples/.explainer-config.toml [hunk 8]
```diff
@@ -0,0 +1,9 @@
+# Any of these config options can or can not be provided
+# Feel free to place this file in your home directory, i.e: cp examples/.explainer-config.toml ~
```
Comment (aamfahim) [inline examples/.explainer-config.toml]: these comments should be removed and just update the `README.md` instead.

File: index.js [hunk 9]
```diff
@@ -16,28 +17,37 @@ program
...
 
 
 
 
   program.argument('<files...>', 'path of the files or directories to process')
   .action(async (files, options) => {
     try {
+      const tomlConfig = TomlChecker();
+      // check for configs provided in toml file
```
Comment (aamfahim) [inline index.js]: the code is very self-explanatory.  No need for this comment.

File: README.md [hunk 10]
```diff
@@ -30,6 +30,7 @@ If you are going to be defining custom Base URL and/or Model refer to [Groq Docu
   - When passing output file name, ensure it has a text readable extension such as `.txt` or `.md`. Otherwise output will not be accessible.
 - **Temperature Control**: Adjust the temperature of the model response, allowing for more or less creativity in the output. Valid temperature is between 0 to 2.
   - Higher the temperature longer the process time.
+- **TOML Config Override**: Uses a TOML config file `.explainer-config.toml` in the `home` directory that contains any or all of the options supported giving precedence to CLI options over TOML config file options
```
Comment (aamfahim) [inline README.md]:
```suggestion
- **TOML Config Override**: Uses a TOML config file `.explainer-config.toml` in the `home` directory that contains any or all of the options supported giving precedence to CLI options over TOML config file options.
```

File: util/TomlChecker.js [hunk 11]
```diff
@@ -0,0 +1,30 @@
+import * as TOML from '@ltd/j-toml';
+import * as os from 'os';
```
Comment (aamfahim) [inline util/TomlChecker.js]: import statements are not consistent with rest of the util files.

File: util/TomlChecker.js [hunk 12]
```diff
@@ -0,0 +1,30 @@
...
+        return {};
+    }
+
+    try {
+        const finalPath = path.resolve(tomlFile);
+        const fileContents = readFileSync(finalPath, 'utf8');
+        return TOML.parse(fileContents);
+    } catch (err) {
+        console.error('Error parsing the TOML file:', err);
+        process.exit(1);
```
Comment (aamfahim) [inline util/TomlChecker.js]: not sure why this is being done this way. The program has only one entry and exit in `index.js`. You can just do a throw here. Follow https://github.com/aamfahim/explainer.js/blob/29c31bd8ab656243296f7370bf41014c40ca75fe/util/processFileWithProvider.js#L27

The error will be caught in the `try....catch` block in `index.js`.

**Review by aamfahim — CHANGES_REQUESTED** [review]
Works great! Great job. Just a few feedback and changes I would prefer.

File: index.js (hunk 1 above)
Comment (Mounayer) [reply index.js]: updated

File: examples/.explainer-config.toml (hunk 2 above)
Comment (Mounayer) [reply examples/.explainer-config.toml]: updated

File: examples/.explainer-config.toml (hunk 3 above)
Comment (Mounayer) [reply examples/.explainer-config.toml]: Updated

File: examples/.explainer-config.toml (hunk 4 above)
Comment (Mounayer) [reply examples/.explainer-config.toml]: updated

File: examples/.explainer-config.toml (hunk 5 above)
Comment (Mounayer) [reply examples/.explainer-config.toml]: updated

File: README.md (hunk 6 above)
Comment (Mounayer) [reply README.md:127]: NO WAY THERE IS TOML SUPPORT!!!! updated

File: README.md (hunk 7 above)
Comment (Mounayer) [reply README.md]: updated

File: examples/.explainer-config.toml (hunk 8 above)
Comment (Mounayer) [reply examples/.explainer-config.toml]: updated

File: index.js (hunk 9 above)
Comment (Mounayer) [reply index.js]: updated

File: README.md (hunk 10 above)
Comment (Mounayer) [reply README.md]: updated

File: util/TomlChecker.js (hunk 11 above)
Comment (Mounayer) [reply util/TomlChecker.js]: updated

File: util/TomlChecker.js (hunk 12 above)
Comment (Mounayer) [reply util/TomlChecker.js]: Actually, don't need to do a throw at all, the readFileSync and parse functions throw their own errors, I just didn't want the program execution to continue and stop it right there, updated!

File: README.md [hunk 13]
```diff
@@ -109,6 +110,28 @@ or
 node index.js examples/bubble_sort.js examples/selection_sort.js
 ```
 
+### TOML Config
+
+You can create a [TOML](https://toml.io/en/) `.explainer-config.toml` config file that contains all of your options for the tool and place it in your `home` directory, i.e. (or simply modify and copy the one that is in the `examples directory`):
+
+To copy to your home directory:
+```bash
```
Comment (aamfahim) [inline README.md:119]: > MD031/blanks-around-fences: Fenced code blocks should be surrounded by blank lines markdownlint [MD031](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md031.md)
```suggestion

```bash
```

File: README.md [hunk 14]
```diff
@@ -109,6 +110,28 @@ or
...
+cp examples/.explainer-config.toml ~
+```
```
Comment (aamfahim) [inline README.md:121]: > MD031/blanks-around-fences: Fenced code blocks should be surrounded by blank lines markdownlint [MD031](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md031.md)

**Review by aamfahim — CHANGES_REQUESTED** [review]

File: README.md (hunk 13 above)
Comment (Mounayer) [reply README.md:119]: updated

File: README.md (hunk 14 above)
Comment (Mounayer) [reply README.md:121]: updated

File: util/TomlChecker.js (hunk 12 above)
Comment (aamfahim) [reply util/TomlChecker.js]: The entire try catch block was removed. Not quite sure why. The try catch should still be there (since TOML can still throw) but should just throw instead, as shown in the referenced file. The error should include message similar to this
> TOML parsing failed: + error.message

File: README.md (hunk 7 above)
Comment (aamfahim) [reply README.md]: As previously discussed,  The command works for `PS` and `WSL`(Linux environment) but it will fail fail `cmd` terminal. Explicit instructions should be provided for users with `cmd`  terminal.

File: util/TomlChecker.js (hunk 12 above)
Comment (Mounayer) [reply util/TomlChecker.js]: Ah you're right, need to throw the correct error message, updated

Comment (aamfahim) [reply util/TomlChecker.js]: also for consistency use `error` instead of `err`

File: README.md (hunk 7 above)
Comment (Mounayer) [reply README.md]: Added an example of how to copy the `.toml` file from `examples` folder into the `home` directory using `Windows` **CMD**

File: util/TomlChecker.js (hunk 12 above)
Comment (Mounayer) [reply util/TomlChecker.js]: updated `err` to `error`

Comment (aamfahim) [reply util/TomlChecker.js]: should be `error.message` in the thrown error as well, as mentioned in the pervious comment.

Comment (Mounayer) [reply util/TomlChecker.js]: Updated the way the error message is structured in code

**Review by aamfahim — APPROVED** [review]
